"""initial migration

Revision ID: e0e38ebf0baa
Revises: 
Create Date: 2024-09-27 20:23:52.007003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0e38ebf0baa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('familia', 'estado_civil')
    op.add_column('membro', sa.Column('estado_civil', sa.String(length=20), nullable=True))
    op.add_column('membro', sa.Column('idade', sa.Integer(), nullable=True))
    op.add_column('membro', sa.Column('sexo', sa.String(length=10), nullable=True))
    op.add_column('membro', sa.Column('carteira_assinada', sa.Boolean(), nullable=True))
    op.add_column('membro', sa.Column('deficiencia_fisica', sa.Boolean(), nullable=True))
    op.alter_column('membro', 'familia_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('membro_ibfk_1', 'membro', type_='foreignkey')
    op.create_foreign_key(None, 'membro', 'familia', ['familia_id'], ['id'])
    op.create_unique_constraint(None, 'usuario', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'membro', type_='foreignkey')
    op.create_foreign_key('membro_ibfk_1', 'membro', 'familia', ['familia_id'], ['id'], ondelete='CASCADE')
    op.alter_column('membro', 'familia_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('membro', 'deficiencia_fisica')
    op.drop_column('membro', 'carteira_assinada')
    op.drop_column('membro', 'sexo')
    op.drop_column('membro', 'idade')
    op.drop_column('membro', 'estado_civil')
    op.add_column('familia', sa.Column('estado_civil', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
